### PR TITLE
Reload profile in XCode shell script

### PR DESCRIPTION
**Pull request by ibratoev**
Shell profile seems to not be properly loaded in my environment. This breaks `asdf`, the version manager I use.

### CODE REVIEW

**Comment by ibratoev** [comment]
@pdobrev Maybe we should remove `PATH=$PATH:/opt/homebrew/bin/` as well. I guess you do that to add `node` and `npm` to the path. This should be done in your local `.profile`.
What do you think?

**Comment by pdobrev** [comment]
Yea, that's good. I don't have a .profile and the path is set up in zshrc, but happy to extract it. Shouldn't belong in the project build step, yeah.

**Comment by pdobrev** [comment]
Does `asdf` compute the path and the env through `~/.profile`?

**Comment by ibratoev** [comment]
I have just this in my `.profile`: . "$HOME/.asdf/asdf.sh" .
ZSH does not load the `.profile` so you need to duplicate the path set up.

**Review by pdobrev — APPROVED** [review]
good to go, I'll adjust the paths to be set in .profile

**Pull request merged**
