### PR TITLE
Fix annoying MacCatalyst build warning

### PR DESCRIPTION
**Pull request by ibratoev**
Fix build warnings related to MacCatalyst support. I don't think we need that at the moment:

"Building for 'macCatalyst', but linking in dylib (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa.tbd) built for 'macOS'"

### CODE REVIEW

**Comment by pdobrev** [comment]
I didn't really know what mac catalyst is, but is seems like it's something that allows you to run iPad apps on macos? 

Where do you get the warning? Weirdly, I get no such warnings.

**Comment by ibratoev** [comment]
I guess because it is available as build target and my XCode selected it by default as I am downloading the iOS SDK at the moment :)

**Review by pdobrev — APPROVED** [review]

**Comment by ibratoev** [comment]
image

**Comment by pdobrev** [comment]
👍 yea we dont need it for now for sure

**Pull request merged**
